openapi: 3.0.0
info:
  title: Notification Client API
  description: "Notifications Client API

    Work in progress. Can be changed completely without notice.

    The events resource is based on the [GOV NL profile for CloudEvents](https://vng-realisatie.github.io/NL-GOV-profile-for-CloudEvents).
    This specification only contains brief descriptions of the attributes of the event. Please refer to the GOV NL profile for additional information.

    This specification is work in progress. It can be changed completely without notice.
    "
  license:
    name: EUPL 1.2
    url: https://opensource.org/licenses/EUPL-1.2
  version: 0.1.0
security:
- JWT-Claims: []
paths:
  /{webhook_path}:
    post:
      operationId: events_post
      summary: Push event
      description: The event will be pushed to the sink (also known as callback url or webhook) provided by the client in the subscription.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
        required: true
      responses:
        '204':
          description: No Content
          headers:
            API-version:
              schema:
                type: string
              description: 'Version of the API. For example: 1.2.1.'
      tags:
      - events
    parameters:
    - name: webhook_path
      in: path
      required: true
      schema:
        type: string
components:
  securitySchemes:
    JWT-Claims:
      bearerFormat: JWT
      scheme: bearer
      type: http
  schemas:
    EventCore:
      required:
      - id
      - source
      - domain
      - specversion
      - type
      type: object
      properties:
        specversion:
          title: specversion
          description: The version of the CloudEvents specification which the event uses. Compliant event producers MUST use a value of 1.0 when referring to this version of the specification.
          type: string
          minLength: 1
          example: "1.0"
        id:
          title: id
          description: Identifies the event. Producers MUST ensure that source + id is unique for each distinct event. SHOULD be a uuid.
          type: string
          minLength: 1
          example: "2febb675-b06c-4f3a-8fc3-f6649aa25ae4"
        source:
          title: source
          description: Identifies the context in which an event happened. SHOULD be a URN notation with 'nld' as namespace identifier. SHOULD contain consecutive a unique identifier of the organization that publishes the event followed by the source system that publishes the event. Involved organizations SHOULD agree on how organizations and systems are uniquely identified (e.g. via the use of OIN, KVK-nummer or eIDAS legal identifier for organization identification);
          type: string
          format: urn
          minLength: 1
          example: "urn:nld:oin:00000001234567890000:systeem:Zaaksysteem"
        domain:
          title: domain
          description: Name of the domain to which the event belongs. Can be seen as the namespace of the event.(This attribute is not listed in the GOV NL profile for CloudEvents)
          type: string
          format: reverse-dns
          minLength: 1
          example: "nl.vng.zaken"
        type:
          title: type
          description: This attribute contains a value describing the type of event. Type SHOULD start with the domain followed by the name of the event. Events SHOULD be expressed in the past tense. If subtypes are required those SHOULD be expressed using a dot '.' between the super and subtype(s). The type MAY contain version information. Version information SHOULD be appended at the end of the string.
          type: string
          format: reverse-dns
          minLength: 1
          example: "nl.vng.zaken.status_gewijzigd"
        time:
          title: time
          description: Timestamp of the event. SHOULD be the timestamp the event was registerd in the source system and NOT the time the event occurred in reality. The exact meaning of time MUST be clearly documented.
          type: string
          format: date-time
          minLength: 1
          example: "2022-03-16T15:29:30.833664Z"
        subscription:
          title: subscription
          description: Uuid of the subscription whose filtercriteria where met by the event. The client once created this subscription by performing a post on the subscription resource of the notificationservice (provider).
          type: string
          format: uuid
          minLength: 1
          example: "a2de4777-1160-4562-a996-b79d27b30c99"
        subscriberReference:
          title: subscriberReference
          description: Reference the client specified when the subscription (see description of the subscription field) was created.
          type: string
          minLength: 1
          example: "1285c6bc-1b54-48d8-96e2-c55a3f970c39"
        datacontenttype:
          title: datacontenttype
          description: Content type of data value. In this version of the API the value MUST be 'application/json'. In future versions of the API other values such as described in [RFC 2046](https://tools.ietf.org/html/rfc2046) MAY be used.
          type: string
          minLength: 1
          example: "application/json"
        dataschema:
          title: dataschema
          description: Identifies the schema that data adheres to.
          type: string
          format: uri
          minLength: 1
          example: "https:www.vng.nl/zgw/zaken/status_gewijzigd_schema.json"
        subject:
          title: subject
          description: Included to be compatible with CloudEvents specification. The GOV NL profile states 'Decision on whether or not to use the attribute and/or the exact interpretation is postponed. To be determined partly on the basis of future agreements about subscription and filtering.'
          type: string
          minLength: 1
        sequence:
          description: Value expressing the relative order of the event. This enables interpretation of data supercedence.
          type: string
          minLength: 1
          example: "42"
        sequencetype:
          description: Specifies the semantics of the sequence attribute. (Currently limited to the value INTEGER).
          type: string
          minLength: 1
          enum:
            - Integer
    EventExtension:
      type: object
      properties:
        <key1>:
          type: string
          example: "<value1>"
        <key2>:
          type: string
          example: "<value2>"
        <keyN>:
          type: string
          example: "<valueN>"
    Event:
      allOf:
        - $ref: "#/components/schemas/EventCore"
        - $ref: "#/components/schemas/EventExtension"
        - properties:
            data:
              type: object
              additionalProperties:
                type: string
            data_base64:
              description: The presence of the data_base64 member clearly indicates that the value is a Base64 encoded binary data, which the serializer MUST decode into a binary runtime data type.
              type: string
              format: byte
            dataref:
              description: A reference to a location where the event payload is stored. If both the data attribute and the dataref attribute are specified their contents MUST be identical.
              type: string
              format: uri
              minLength: 1
